// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcfcidtyteggemsrijjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZmNpZHR5dGVnZ2Vtc3JpampzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTEwMTYsImV4cCI6MjA2MzY4NzAxNn0.rV3v9Znx47-e0hhKYMe2CYZw63iiZtH8hk7tVqc6HJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);